
print('|                      .                       |')
print('|                    .` `.                     |')
print('|                  .`     `.                   |')
print('|                .`         `.                 |')
print('|              .`      N      `.               |')
print('|            .`        |        `.             |')
print('|          .`          |          `.           |')
print('|        .`          ] |  [         `.         |')
print('|      .`         ]    |    [         `.       |')
print('|    .`         ]      |      [         `.     |')
print('|  .`     W---]--------O--------[---E     `.   |')
print('|   `.          ]      |      [          .`    |')
print('|     `.          ]    |    [          .`      |')
print('|       `.          ]  |  [          .`        |')
print('|         `.          ]|[          .`          |')
print('|           `.         |         .`            |')
print('|             `.       S       .`              |')
print('|               `.           .`                |')
print('|                 `.       .`                  |')
print('|                   `.   .`                    |')
print('|                     `.`                      |')                     
